name: Manually Restart

on:
  # start manually
  workflow_dispatch:


jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: SSH Login
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          request_pty: true
          key: ${{ secrets.KEY }}

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        user:
          - himo
          - himowd
          - lyan
          - nada
          - sanaa
          - suha
    steps:
      - name: Deploy for ${{ matrix.user }}
        needs: login
        script: |
          become ${{ matrix.user }} sh -c "toolforge jobs list; toolforge jobs flush; toolforge jobs load ${{ matrix.user }}-jobs.yaml"
